# Docker Build & Push on Tag
name: Docker Build
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  docker-build-push:
    runs-on: ubuntu-20.04
    timeout-minutes: 40
    steps:
      - uses: actions/checkout@v1
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Build the tagged Docker image
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        run: |
          echo $RELEASE_VERSION
          echo ${{ steps.vars.outputs.tag }}
          docker build . --file Dockerfile --build-arg username=${{ secrets.GH_USERNAME }} --build-arg token=${{ secrets.GH_TOKEN }} --tag samagragovernance/transformer:$RELEASE_VERSION
      - name: Push the tagged Docker image
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        run: docker push samagragovernance/transformer:$RELEASE_VERSION
